#! /bin/sh

#Initialize sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#Initialize Polybar
$HOME/.config/polybar/launch.sh

#Initialize feh(Background)
feh --bg-scale ~/Backgrounds/the-wind-rises.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='any.!occupied' state=tiled follow=on
bspc rule -a Zathura state=tiled
